# Milk Quality Prediction

Import library yang dibutuhkan

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn import preprocessing

Membaca Dataset

In [3]:
data = pd.read_csv('milknew.csv')
data.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

Label Encoding

In [4]:
label_encoder = preprocessing.LabelEncoder()
data['Grade']= label_encoder.fit_transform(data['Grade'])
data['Grade'].unique()

array([0, 1, 2])

Menampilkan informasi umum dataset

In [5]:
print("Jumlah baris dan kolom:", data.shape)
print("\nInformasi Kolom:")
print(data.info())


Jumlah baris dan kolom: (1059, 8)

Informasi Kolom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   int64  
dtypes: float64(1), int64(7)
memory usage: 66.3 KB
None


Menampilkan nilai-nilai dari kolom target Grade, yang merupakan hasil prediksi (high = 0, low = 1, medium = 2).

In [6]:
print(data ['Grade'].values)

[0 0 1 ... 1 0 1]


Memisahkan fitur dan target

In [7]:
X = data.drop(columns='Grade') 
y = data['Grade']  # pastikan nama outcome sesuai

print("Fitur:", X.columns.tolist())
print("Jumlah data:", len(X))

Fitur: ['pH', 'Temprature', 'Taste', 'Odor', 'Fat ', 'Turbidity', 'Colour']
Jumlah data: 1059


Membagi data menjadi data latih dan data uji

In [31]:
# Split data latih dan uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi fitur
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


Membuat dan melatih model Support Vector Classification

In [32]:
# Buat model SVM dengan kernel RBF
model = SVC(kernel='rbf', random_state=42)
model.fit(X_train, y_train)

SVC(random_state=42)

Memprediksi hasil dari data uji

In [33]:
y_pred = model.predict(X_test)
print(y_pred)

[0 1 1 2 2 1 1 0 1 0 1 2 0 2 1 1 0 2 2 2 1 2 0 2 2 0 2 0 1 1 2 0 0 0 0 2 2
 0 2 2 1 1 1 0 0 1 0 0 2 0 2 1 1 2 2 1 0 1 1 2 2 1 0 0 0 1 2 2 1 2 1 1 0 2
 1 1 1 2 1 2 2 2 0 0 2 2 0 1 2 0 1 1 0 0 1 2 0 0 0 0 1 1 1 1 2 2 1 1 2 0 0
 2 2 1 0 0 2 1 0 0 2 1 1 1 2 0 2 2 0 2 1 2 1 2 1 1 2 1 2 2 2 0 1 2 1 1 0 1
 1 2 2 2 0 1 2 1 1 0 1 0 2 2 2 1 2 0 1 1 2 1 0 0 1 1 0 1 2 2 2 2 1 2 0 1 0
 1 2 0 2 1 1 2 0 1 0 1 1 0 2 2 0 2 0 0 2 1 2 0 2 2 0 0]


Actual y_test value

In [34]:
print(y_test.values)

[0 1 1 2 2 1 1 0 1 2 1 2 0 2 1 1 0 2 2 2 1 2 0 2 2 2 1 0 1 1 2 0 0 2 0 2 2
 0 2 2 1 1 1 2 0 1 0 0 2 0 2 1 1 2 2 1 0 1 1 2 2 1 0 0 0 1 2 2 1 2 1 1 0 2
 1 1 1 2 1 2 2 2 0 0 2 2 2 1 2 0 1 1 0 2 1 2 0 0 1 0 1 1 1 1 2 2 1 1 2 0 0
 2 2 1 0 1 2 1 1 0 2 1 1 1 2 0 2 2 0 2 1 2 1 2 1 1 2 1 2 2 2 0 1 2 1 1 0 1
 1 2 2 2 2 1 2 1 1 0 1 0 2 2 2 1 2 0 1 1 2 1 2 0 1 1 0 1 2 2 2 2 1 2 0 1 0
 1 2 0 2 1 1 2 2 1 0 1 1 0 2 2 2 2 0 0 2 1 2 2 2 2 0 0]


Evaluasi model

In [35]:
print("Akurasi:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Akurasi: 0.9292452830188679
Confusion Matrix:
 [[48  0  0]
 [ 3 74  1]
 [11  0 75]]
Classification Report:
               precision    recall  f1-score   support

           0       0.77      1.00      0.87        48
           1       1.00      0.95      0.97        78
           2       0.99      0.87      0.93        86

    accuracy                           0.93       212
   macro avg       0.92      0.94      0.92       212
weighted avg       0.94      0.93      0.93       212

